language: php

matrix:
  fast_finish: true

  include:
      - php: 5.5
        env: UNIT_TESTS=yes FUNCTIONAL_TESTS=yes PHP_LINT=yes XLF_CHECK=yes SUBMODULE_TEST=yes
      - php: 5.6
        env: UNIT_TESTS=yes FUNCTIONAL_TESTS=yes PHP_LINT=yes
      - php: 7
        env: UNIT_TESTS=yes FUNCTIONAL_TESTS=yes PHP_LINT=yes

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    secure: NGVAI0ayw2h9pB2bi2u9AkfV1OKa2LCrGXNtxAvQhFxKW28qmeOUehFuacxpvCI5fA8Ae7oVo2Ba0vcpb5a3uJry1lMpxcn9Ic+voB7SwlCuL6Rx/vntPkYUH+58cC3t40yHKArCUE9KCJA6znNCaZ7MyG6dWHgry0cvAjVOQzE=

before_script:
  - phpenv config-rm xdebug.ini
  - rm -rf typo3/sysext/compatibility6
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer install

script:
  - >
    if [[ "$UNIT_TESTS" == "yes" ]]; then
      echo;
      echo "Running unit tests";
      phpunit -c phpunit.xml.dist
    fi
  - >
    if [[ "$PHP_LINT" == "yes" ]]; then
        echo;
        echo "Running php lint";
        find Classes/ -name \*.php -not -path "vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
    fi