<?php

/*********************************************************************
* Extension configuration file for ext "yag".
*
* Generated by ext 10-10-2015 13:45 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array(
  'title' => 'Yet Another Gallery',
  'description' => 'Scalable, powerful, easy-to-manage Gallery Extension for TYPO3. Features Frontend with lightbox, Backend Administration Module and Themes for personalization. See http://www.yag-gallery.de for demonstration.',
  'category' => 'plugin',
  'author' => 'Daniel Lienert',
  'author_email' => 'typo3@lienert.cc',
  'author_company' => '',
  'shy' => '',
  'dependencies' => 'pt_extlist,pt_extbase',
  'conflicts' => '',
  'priority' => '',
  'module' => '',
  'state' => 'stable',
  'internal' => '',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '4.1.0',
  'constraints' =>
  array(
    'depends' =>
    array(
      'pt_extlist' => '2.0.4',
      'pt_extbase' => '2.0.0',
      'typo3' => '7.6.0-7.6.99',
    ),
    'conflicts' =>
    array(
    ),
    'suggests' =>
    array(
    ),
  ),
  'suggests' =>
  array(
  ),
  'comment' => 'Compatibility fixes for TYPO3 7.5 and minor bugfixes',
  'user' => 'daniellienert',
);
